language: objective-c
osx_image: xcode7.1

before_install:
  - brew update
  - brew upgrade xctool
  - brew install carthage
  # - carthage bootstrap --verbose

script:
  # - xcodebuild test -scheme Result-Mac
  - xcodebuild test -scheme Sometimes-iOS -sdk iphonesimulator

notifications:
  email: false
